baseURL = 'https://tech.mdflare.com/'
languageCode = 'ko'
title = 'Tech Side Story'
theme = 'stack'

[params]
  description = 'ë§¤ì¼ ë°°ìš°ê³  ê¸°ë¡í•˜ëŠ” ê¸°ìˆ  ë¸”ë¡œê·¸'
  mainSections = ['post']
  favicon = '/favicon.ico'

[params.sidebar]
  emoji = 'ğŸ”§'
  subtitle = 'ë§¤ì¼ ë°°ìš°ê³  ê¸°ë¡í•˜ëŠ” ê¸°ìˆ  ë¸”ë¡œê·¸'

[params.article]
  math = false
  toc = true
  readingTime = true

[params.comments]
  enabled = false

[markup]
  [markup.highlight]
    lineNos = true
    style = 'monokai'
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Archives'
    url = '/archives'
    weight = 2
  [[menu.main]]
    name = 'Search'
    url = '/search'
    weight = 3
