baseURL = 'https://tech.mdflare.com/'
languageCode = 'ko'
title = 'Tech Side Story'
theme = 'stack'

[params]
  description = 'ë§¤ì¼ ë°°ìš°ê³  ê¸°ë¡í•˜ëŠ” ê¸°ìˆ  ë¸”ë¡œê·¸'
  mainSections = ['post']
  favicon = '/favicon.ico'

[params.sidebar]
  emoji = 'ğŸ”§'
  subtitle = 'ë§¤ì¼ ë°°ìš°ê³  ê¸°ë¡í•˜ëŠ” ê¸°ìˆ  ë¸”ë¡œê·¸'

[params.article]
  math = false
  toc = true
  readingTime = true

[params.comments]
  enabled = true
  provider = "giscus"

[params.comments.giscus]
  repo = "sskcoach/tech-blog"
  repoID = "R_kgDORObi7Q"
  category = "General"
  categoryID = "DIC_kwDORObi7c4C2Ren"
  mapping = "pathname"
  lightTheme = "light"
  darkTheme = "dark_dimmed"
  reactionsEnabled = 1
  emitMetadata = 0

[markup]
  [markup.highlight]
    lineNos = true
    style = 'monokai'
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Archives'
    url = '/archives'
    weight = 2
  [[menu.main]]
    name = 'Search'
    url = '/search'
    weight = 3
